// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackYourExpenseApi.DbContexts;

namespace TrackYourExpenseApi.Migrations
{
    [DbContext(typeof(ExpensesContext))]
    partial class ExpensesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrackYourExpenseApi.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7855e981-32bc-4ce2-a32e-89421876462d"),
                            Description = "Monthly Rent Expense",
                            Type = "Rent"
                        },
                        new
                        {
                            Id = new Guid("390d54b7-ed6e-42b1-99cb-109aafe1ae2e"),
                            Description = "Monthly Rent Expense",
                            Type = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("TrackYourExpenseApi.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfTransaction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExpenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId")
                        .IsUnique()
                        .HasFilter("[ExpenseId] IS NOT NULL");

                    b.ToTable("Transacations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cab11e4c-62b8-449d-8197-a5c788af85b4"),
                            Amount = 0.0,
                            DateOfTransaction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly Car Rental Expenses",
                            Text = "Car Rent"
                        },
                        new
                        {
                            Id = new Guid("f6489e6f-45af-4cb1-95ce-1ac658f891af"),
                            Amount = 0.0,
                            DateOfTransaction = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly Rent Expense",
                            Text = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("TrackYourExpenseApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TrackYourExpenseApi.Entities.Transaction", b =>
                {
                    b.HasOne("TrackYourExpenseApi.Entities.Expense", "Expense")
                        .WithOne("Transaction")
                        .HasForeignKey("TrackYourExpenseApi.Entities.Transaction", "ExpenseId");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("TrackYourExpenseApi.Entities.Expense", b =>
                {
                    b.Navigation("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
